import Head from 'next/head';
import Header from '../components/header';
import Footer from '../components/footer';




export default function Home() {
  return (
    <div>
      <Head>
        <title>Monochrome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <Footer></Footer>

      </div>
  );
}
